### PR TITLE
fix: export HeadingLevel type

### LINKED ISSUE #2115: [fix] HeadingLevel type is not exported
**ReactUSWDS Version & USWDS Version:**

TypeScript compilation of projects that use react-uswds fails because the HeadingLevel type introduced in #1988 is not included in the generated index.d.ts file.

**Describe the bug**

See https://github.com/tachgsfc/gcn.nasa.gov/pull/55#issuecomment-1133118204.

**To Reproduce**
```
$ npx tsc -p .
node_modules/@trussworks/react-uswds/lib/components/Accordion/Accordion.d.ts:8:19 - error TS2304: Cannot find name 'HeadingLevel'.

8     headingLevel: HeadingLevel;
                    ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/Alert/Alert.d.ts:5:19 - error TS2304: Cannot find name 'HeadingLevel'.

5     headingLevel: HeadingLevel;
                    ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/Collection/CollectionHeading.d.ts:3:19 - error TS2304: Cannot find name 'HeadingLevel'.

3     headingLevel: HeadingLevel;
                    ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/IconList/IconListTitle/IconListTitle.d.ts:8:11 - error TS2304: Cannot find name 'HeadingLevel'.

8     type: HeadingLevel;
            ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/ProcessList/ProcessListHeading/ProcessListHeading.d.ts:8:11 - error TS2304: Cannot find name 'HeadingLevel'.

8     type: HeadingLevel;
            ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/stepindicator/StepIndicator/StepIndicator.d.ts:12:19 - error TS2304: Cannot find name 'HeadingLevel'.

12     headingLevel: HeadingLevel;
                     ~~~~~~~~~~~~


Found 6 errors in 6 files.

Errors  Files
     1  node_modules/@trussworks/react-uswds/lib/components/Accordion/Accordion.d.ts:8
     1  node_modules/@trussworks/react-uswds/lib/components/Alert/Alert.d.ts:5
     1  node_modules/@trussworks/react-uswds/lib/components/Collection/CollectionHeading.d.ts:3
     1  node_modules/@trussworks/react-uswds/lib/components/IconList/IconListTitle/IconListTitle.d.ts:8
     1  node_modules/@trussworks/react-uswds/lib/components/ProcessList/ProcessListHeading/ProcessListHeading.d.ts:8
     1  node_modules/@trussworks/react-uswds/lib/components/stepindicator/StepIndicator/StepIndicator.d.ts:12
```

**Expected behavior**

Successful TypeScript compilation

**Device and Browser Information (please complete the following information if describing a UI bug):**

react-uswds 3.0.2

### PR DESCRIPTION
**Pull request by lpsinger**
# Summary

## Related Issues or PRs

Fixes #2115.

### CODE REVIEW

**Comment by rogeruiz** [comment]
Thank you for bringing up this issue and submitting this PR @lpsinger we will be integrating this into our default branch sometime today. 

I also wanted to ask if the reproduction command you posted in your issue is enough of a test for this kind of bug? I would like to incorporate testing TypeScript type checking into our CI process to prevent these sort of issues in the future.

**Comment by brandonlenz** [comment]
I want to understand this better before merging. I’m not fully clear why this type must be

1. non-global (we have other global types used internally)
2. Exported (I’m fine with exporting the type along with other types for consistency and convenience, but that’s a paradigm we haven’t needed to do before, even for props that are externally exposed but use internally defined types)

I’m curious why this one specifically is causing problems

**Comment by lpsinger** [comment]
I really don't know why this type is causing problems, but you can easily verify before this patch that the declaration was not present in the lib directory.

**Comment by brandonlenz** [comment]
@lpsinger I'm looking in to updating things on the react-uswds side to properly emit types.

Meanwhile, unless you have other reasons for it, you might consider excluding node_modules from typescript compilation
```
"exclude": [
    "node_modules"
]
```

Or by _not_ including `node_modules` tsx files in typescript compilation to begin with by setting `include` to `"src/**/*.ts", "src/**/*.tsx"` in [your tsconfig](https://github.com/tachgsfc/gcn.nasa.gov/blob/main/tsconfig.json).

**Comment by brandonlenz** [comment]
@lpsinger I've opened #2134 which also accomplishes this, but fixes some other quirks in how types are checked vs how the lib is built. Closing this, but please follow along there.
