### ISSUE TITLE
[fix] HeadingLevel type is not exported

### ISSUE THREAD

**Issue by lpsinger** [trussworks/react-uswds#2115]
**ReactUSWDS Version & USWDS Version:**

TypeScript compilation of projects that use react-uswds fails because the HeadingLevel type introduced in #1988 is not included in the generated index.d.ts file.

**Describe the bug**

See https://github.com/tachgsfc/gcn.nasa.gov/pull/55#issuecomment-1133118204.

**To Reproduce**
```
$ npx tsc -p .
node_modules/@trussworks/react-uswds/lib/components/Accordion/Accordion.d.ts:8:19 - error TS2304: Cannot find name 'HeadingLevel'.

8     headingLevel: HeadingLevel;
                    ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/Alert/Alert.d.ts:5:19 - error TS2304: Cannot find name 'HeadingLevel'.

5     headingLevel: HeadingLevel;
                    ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/Collection/CollectionHeading.d.ts:3:19 - error TS2304: Cannot find name 'HeadingLevel'.

3     headingLevel: HeadingLevel;
                    ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/IconList/IconListTitle/IconListTitle.d.ts:8:11 - error TS2304: Cannot find name 'HeadingLevel'.

8     type: HeadingLevel;
            ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/ProcessList/ProcessListHeading/ProcessListHeading.d.ts:8:11 - error TS2304: Cannot find name 'HeadingLevel'.

8     type: HeadingLevel;
            ~~~~~~~~~~~~

node_modules/@trussworks/react-uswds/lib/components/stepindicator/StepIndicator/StepIndicator.d.ts:12:19 - error TS2304: Cannot find name 'HeadingLevel'.

12     headingLevel: HeadingLevel;
                     ~~~~~~~~~~~~


Found 6 errors in 6 files.

Errors  Files
     1  node_modules/@trussworks/react-uswds/lib/components/Accordion/Accordion.d.ts:8
     1  node_modules/@trussworks/react-uswds/lib/components/Alert/Alert.d.ts:5
     1  node_modules/@trussworks/react-uswds/lib/components/Collection/CollectionHeading.d.ts:3
     1  node_modules/@trussworks/react-uswds/lib/components/IconList/IconListTitle/IconListTitle.d.ts:8
     1  node_modules/@trussworks/react-uswds/lib/components/ProcessList/ProcessListHeading/ProcessListHeading.d.ts:8
     1  node_modules/@trussworks/react-uswds/lib/components/stepindicator/StepIndicator/StepIndicator.d.ts:12
```

**Expected behavior**

Successful TypeScript compilation

**Device and Browser Information (please complete the following information if describing a UI bug):**

react-uswds 3.0.2
